BLD: Create OpenBLAS shared object
HaoZeke/OpenBLAS pull request #24
Opened 2024-08-13 09:43 UTC by mtsokol

WIP

2024-08-13 13:05 UTC, HaoZeke requested changes

2024-08-13 13:05 UTC, HaoZeke commented on meson.build
> +                              link_whole: [_openblas],
Perhaps using `both_libs` is more idiomatic?
https://mesonbuild.com/Reference-manual_functions.html#both_libraries

2024-08-13 13:05 UTC, HaoZeke commented on lapack-netlib/SRC/meson.build
> +             install_dir: '../../pkgconfig',
Can this be replaced with a project scoped variable?

2024-08-14 10:45 UTC, mtsokol commented on lapack-netlib/SRC/meson.build
> +             install_dir: '../../pkgconfig',
Done!

2024-08-14 10:46 UTC, mtsokol commented on meson.build
> +                              link_whole: [_openblas],
Sure! I used `both_libraries` function instead.

2024-08-14 13:02 UTC, HaoZeke approved these changes

2024-08-14 13:03 UTC, merged

2024-08-14 13:03 UTC, HaoZeke commented
Thanks @mtsokol